const translations = {
    en: {
        name: "English",
        sono: "Sono",
        pageTitle: "Sono - Sound Matching Game",
        createNewList: "Create New Set",
        retrieveList: "Retrieve Set",
        enterPassphrase: "Enter passphrase",
        load: "Load",
        enterSubject: "Enter a subject",
        enter: "Enter",
        save: "Save",
        yourPassphrase: "Your Passphrase",
        copy: "Copy",
        share: "Share",
        proceed: "Start Game",
        settings: "Settings",
        addAtLeastOneSubject: "Please add at least one subject",
        passphraseCopied: "Passphrase copied to clipboard!",
        copyPassphrase: "Copy this passphrase:",
        invalidPassphrase: "Invalid passphrase",
        visitDendriteAT: "Visit Dendrite AT",
        languageSettings: "Language Settings",
        visionAccessibility: "Vision Accessibility",
        gameSettings: "Game Settings",
        emptyStateMessage: "Your subjects will appear here. Start typing above!",
        gridSize: "Grid Size",
        visualMode: "Visual Mode",
        graphics: "Graphics",
        photos: "Photos",
        cardBehavior: "Card Behavior",
        removeCards: "Remove Cards",
        crossOut: "Cross Out",
        masterVolume: "Sound Volume",
        feedbackVolume: "Feedback Volume",
        enableCueing: "Enable Visual Cueing",
        cueDelay: "Cue Delay",
        cueIntensity: "Cue Intensity",
        subtle: "Subtle",
        gentle: "Gentle",
        obvious: "Obvious",
        cueType: "Cue Type",
        glow: "Glow",
        wiggle: "Wiggle",
        bounce: "Bounce",
        playAgain: "Play Again",
        gameComplete: "Game Complete!",
        errorPlayingSound: "Error playing sound",
        back: "Back",
        subject: "subject",
        subjects: "subjects",
        invalidSubject: "Invalid subject",
        duplicateSubject: "Subject already added",
        needMoreSubjects: "Need at least",
        forGridSize: "subjects for selected grid size",
        loadingGame: "Loading game...",
        replaySound: "Replay Sound",
        cardsRemaining: "cards remaining",
        printOptions: "Print Options",
        printType: "Print Type",
        bingoCards: "Bingo Cards",
        cueCards3x3: "Cue Cards (3×3\")",
        cueCards4x4: "Cue Cards (4×4\")",
        numberOfSheets: "Number of Sheets",
        gridSizePrint: "Grid Size (n × n)",
        generatePDF: "Generate PDF"
    },
    zh: {
        name: "中文",
        signShare: "手语分享",
        pageTitle: "手语分享 - ASL词汇表",
        createNewList: "创建新列表",
        retrieveList: "检索列表",
        enterPassphrase: "输入密码短语",
        load: "加载",
        enterWord: "输入一个词",
        enter: "输入",
        save: "保存",
        yourSharePhrase: "您的分享短语",
        copy: "复制",
        share: "分享",
        proceed: "继续",
        viewPassphrase: "查看密码短语",
        editList: "编辑列表",
        addAtLeastOneWord: "请至少添加一个词",
        passphraseCopied: "密码短语已复制到剪贴板！",
        copyPassphrase: "复制此密码短语：",
        invalidPassphrase: "无效的密码短语",
        visitDendriteAT: "访问 Dendrite AT",
        languageSettings: "语言设置",
        visionAccessibility: "视觉辅助功能",
        resourceSettings: "资源设置",
        emptyStateMessage: "您的词汇将显示在这里。开始在上方输入！"
    },
    hi: {
        name: "हिन्दी",
        signShare: "साइन शेयर",
        pageTitle: "साइन शेयर - ASL शब्द सूची",
        createNewList: "नई सूची बनाएं",
        retrieveList: "सूची पुनर्प्राप्त करें",
        enterPassphrase: "पासफ्रेज़ दर्ज करें",
        load: "लोड करें",
        enterWord: "एक शब्द दर्ज करें",
        enter: "दर्ज करें",
        save: "सहेजें",
        yourSharePhrase: "आपका शेयर फ्रेज़",
        copy: "कॉपी करें",
        share: "शेयर करें",
        proceed: "आगे बढ़ें",
        viewPassphrase: "पासफ्रेज़ देखें",
        editList: "सूची संपादित करें",
        addAtLeastOneWord: "कृपया कम से कम एक शब्द जोड़ें",
        passphraseCopied: "पासफ्रेज़ क्लिपबोर्ड पर कॉपी किया गया!",
        copyPassphrase: "इस पासफ्रेज़ को कॉपी करें:",
        invalidPassphrase: "अमान्य पासफ्रेज़",
        visitDendriteAT: "Dendrite AT पर जाएं",
        languageSettings: "भाषा सेटिंग्स",
        visionAccessibility: "दृष्टि सुलभता",
        resourceSettings: "संसाधन सेटिंग्स",
        emptyStateMessage: "आपके शब्द यहां दिखाई देंगे। ऊपर टाइप करना शुरू करें!"
    },
    es: {
        name: "Español",
        signShare: "Compartir Señas",
        pageTitle: "Compartir Señas - Listas de Palabras ASL",
        createNewList: "Crear Nueva Lista",
        retrieveList: "Recuperar Lista",
        enterPassphrase: "Ingrese la frase de contraseña",
        load: "Cargar",
        enterWord: "Ingrese una palabra",
        enter: "Ingresar",
        save: "Guardar",
        yourSharePhrase: "Su Frase de Compartir",
        copy: "Copiar",
        share: "Compartir",
        proceed: "Continuar",
        viewPassphrase: "Ver Frase de Contraseña",
        editList: "Editar Lista",
        addAtLeastOneWord: "Por favor agregue al menos una palabra",
        passphraseCopied: "¡Frase de contraseña copiada al portapapeles!",
        copyPassphrase: "Copie esta frase de contraseña:",
        invalidPassphrase: "Frase de contraseña inválida",
        visitDendriteAT: "Visitar Dendrite AT",
        languageSettings: "Configuración de Idioma",
        visionAccessibility: "Accesibilidad Visual",
        resourceSettings: "Configuración de Recursos",
        emptyStateMessage: "Sus palabras aparecerán aquí. ¡Comience a escribir arriba!"
    },
    fr: {
        name: "Français",
        signShare: "Partage de Signes",
        pageTitle: "Partage de Signes - Listes de Mots ASL",
        createNewList: "Créer une Nouvelle Liste",
        retrieveList: "Récupérer la Liste",
        enterPassphrase: "Entrez la phrase secrète",
        load: "Charger",
        enterWord: "Entrez un mot",
        enter: "Entrer",
        save: "Enregistrer",
        yourSharePhrase: "Votre Phrase de Partage",
        copy: "Copier",
        share: "Partager",
        proceed: "Continuer",
        viewPassphrase: "Voir la Phrase Secrète",
        editList: "Modifier la Liste",
        addAtLeastOneWord: "Veuillez ajouter au moins un mot",
        passphraseCopied: "Phrase secrète copiée dans le presse-papiers !",
        copyPassphrase: "Copiez cette phrase secrète :",
        invalidPassphrase: "Phrase secrète invalide",
        visitDendriteAT: "Visiter Dendrite AT",
        languageSettings: "Paramètres de Langue",
        visionAccessibility: "Accessibilité Visuelle",
        resourceSettings: "Paramètres de Ressources",
        emptyStateMessage: "Vos mots apparaîtront ici. Commencez à taper ci-dessus !"
    },
    ar: {
        name: "العربية",
        signShare: "مشاركة الإشارات",
        pageTitle: "مشاركة الإشارات - قوائم كلمات ASL",
        createNewList: "إنشاء قائمة جديدة",
        retrieveList: "استرجاع القائمة",
        enterPassphrase: "أدخل عبارة المرور",
        load: "تحميل",
        enterWord: "أدخل كلمة",
        enter: "إدخال",
        save: "حفظ",
        yourSharePhrase: "عبارة المشاركة الخاصة بك",
        copy: "نسخ",
        share: "مشاركة",
        proceed: "متابعة",
        viewPassphrase: "عرض عبارة المرور",
        editList: "تحرير القائمة",
        addAtLeastOneWord: "يرجى إضافة كلمة واحدة على الأقل",
        passphraseCopied: "تم نسخ عبارة المرور إلى الحافظة!",
        copyPassphrase: "انسخ عبارة المرور هذه:",
        invalidPassphrase: "عبارة مرور غير صالحة",
        visitDendriteAT: "زيارة Dendrite AT",
        languageSettings: "إعدادات اللغة",
        visionAccessibility: "إمكانية الوصول البصري",
        resourceSettings: "إعدادات الموارد",
        emptyStateMessage: "ستظهر كلماتك هنا. ابدأ الكتابة أعلاه!"
    },
    bn: {
        name: "বাংলা",
        signShare: "সাইন শেয়ার",
        pageTitle: "সাইন শেয়ার - ASL শব্দ তালিকা",
        createNewList: "নতুন তালিকা তৈরি করুন",
        retrieveList: "তালিকা পুনরুদ্ধার করুন",
        enterPassphrase: "পাসফ্রেজ প্রবেশ করান",
        load: "লোড করুন",
        enterWord: "একটি শব্দ প্রবেশ করান",
        enter: "প্রবেশ করান",
        save: "সংরক্ষণ করুন",
        yourSharePhrase: "আপনার শেয়ার ফ্রেজ",
        copy: "কপি করুন",
        share: "শেয়ার করুন",
        proceed: "এগিয়ে যান",
        viewPassphrase: "পাসফ্রেজ দেখুন",
        editList: "তালিকা সম্পাদনা করুন",
        addAtLeastOneWord: "অনুগ্রহ করে কমপক্ষে একটি শব্দ যোগ করুন",
        passphraseCopied: "পাসফ্রেজ ক্লিপবোর্ডে কপি করা হয়েছে!",
        copyPassphrase: "এই পাসফ্রেজটি কপি করুন:",
        invalidPassphrase: "অবৈধ পাসফ্রেজ",
        visitDendriteAT: "Dendrite AT পরিদর্শন করুন",
        languageSettings: "ভাষা সেটিংস",
        visionAccessibility: "দৃষ্টি অ্যাক্সেসযোগ্যতা",
        resourceSettings: "রিসোর্স সেটিংস",
        emptyStateMessage: "আপনার শব্দগুলি এখানে প্রদর্শিত হবে। উপরে টাইপ করা শুরু করুন!"
    },
    pt: {
        name: "Português",
        signShare: "Compartilhar Sinais",
        pageTitle: "Compartilhar Sinais - Listas de Palavras ASL",
        createNewList: "Criar Nova Lista",
        retrieveList: "Recuperar Lista",
        enterPassphrase: "Digite a frase secreta",
        load: "Carregar",
        enterWord: "Digite uma palavra",
        enter: "Entrar",
        save: "Salvar",
        yourSharePhrase: "Sua Frase de Compartilhamento",
        copy: "Copiar",
        share: "Compartilhar",
        proceed: "Prosseguir",
        viewPassphrase: "Ver Frase Secreta",
        editList: "Editar Lista",
        addAtLeastOneWord: "Por favor, adicione pelo menos uma palavra",
        passphraseCopied: "Frase secreta copiada para a área de transferência!",
        copyPassphrase: "Copie esta frase secreta:",
        invalidPassphrase: "Frase secreta inválida",
        visitDendriteAT: "Visitar Dendrite AT",
        languageSettings: "Configurações de Idioma",
        visionAccessibility: "Acessibilidade Visual",
        resourceSettings: "Configurações de Recursos",
        emptyStateMessage: "Suas palavras aparecerão aqui. Comece a digitar acima!"
    },
    ru: {
        name: "Русский",
        signShare: "Обмен жестами",
        pageTitle: "Обмен жестами - Списки слов ASL",
        createNewList: "Создать новый список",
        retrieveList: "Получить список",
        enterPassphrase: "Введите парольную фразу",
        load: "Загрузить",
        enterWord: "Введите слово",
        enter: "Ввести",
        save: "Сохранить",
        yourSharePhrase: "Ваша фраза обмена",
        copy: "Копировать",
        share: "Поделиться",
        proceed: "Продолжить",
        viewPassphrase: "Просмотреть парольную фразу",
        editList: "Редактировать список",
        addAtLeastOneWord: "Пожалуйста, добавьте хотя бы одно слово",
        passphraseCopied: "Парольная фраза скопирована в буфер обмена!",
        copyPassphrase: "Скопируйте эту парольную фразу:",
        invalidPassphrase: "Неверная парольная фраза",
        visitDendriteAT: "Посетить Dendrite AT",
        languageSettings: "Настройки языка",
        visionAccessibility: "Визуальная доступность",
        resourceSettings: "Настройки ресурсов",
        emptyStateMessage: "Ваши слова появятся здесь. Начните печатать выше!"
    },
    ja: {
        name: "日本語",
        signShare: "サイン共有",
        pageTitle: "サイン共有 - ASL単語リスト",
        createNewList: "新しいリストを作成",
        retrieveList: "リストを取得",
        enterPassphrase: "パスフレーズを入力",
        load: "読み込み",
        enterWord: "単語を入力",
        enter: "入力",
        save: "保存",
        yourSharePhrase: "共有フレーズ",
        copy: "コピー",
        share: "共有",
        proceed: "続行",
        viewPassphrase: "パスフレーズを表示",
        editList: "リストを編集",
        addAtLeastOneWord: "少なくとも1つの単語を追加してください",
        passphraseCopied: "パスフレーズがクリップボードにコピーされました！",
        copyPassphrase: "このパスフレーズをコピー：",
        invalidPassphrase: "無効なパスフレーズ",
        visitDendriteAT: "Dendrite ATにアクセス",
        languageSettings: "言語設定",
        visionAccessibility: "視覚的アクセシビリティ",
        resourceSettings: "リソース設定",
        emptyStateMessage: "ここに単語が表示されます。上で入力を開始してください！"
    },
    de: {
        name: "Deutsch",
        signShare: "Gebärden teilen",
        pageTitle: "Gebärden teilen - ASL Wortlisten",
        createNewList: "Neue Liste erstellen",
        retrieveList: "Liste abrufen",
        enterPassphrase: "Passphrase eingeben",
        load: "Laden",
        enterWord: "Wort eingeben",
        enter: "Eingeben",
        save: "Speichern",
        yourSharePhrase: "Ihre Freigabephrase",
        copy: "Kopieren",
        share: "Teilen",
        proceed: "Fortfahren",
        viewPassphrase: "Passphrase anzeigen",
        editList: "Liste bearbeiten",
        addAtLeastOneWord: "Bitte fügen Sie mindestens ein Wort hinzu",
        passphraseCopied: "Passphrase in die Zwischenablage kopiert!",
        copyPassphrase: "Diese Passphrase kopieren:",
        invalidPassphrase: "Ungültige Passphrase",
        visitDendriteAT: "Dendrite AT besuchen",
        languageSettings: "Spracheinstellungen",
        visionAccessibility: "Visuelle Zugänglichkeit",
        resourceSettings: "Ressourceneinstellungen",
        emptyStateMessage: "Ihre Wörter werden hier angezeigt. Beginnen Sie oben zu tippen!"
    },
    id: {
        name: "Bahasa Indonesia",
        signShare: "Bagikan Tanda",
        pageTitle: "Bagikan Tanda - Daftar Kata ASL",
        createNewList: "Buat Daftar Baru",
        retrieveList: "Ambil Daftar",
        enterPassphrase: "Masukkan frasa sandi",
        load: "Muat",
        enterWord: "Masukkan kata",
        enter: "Masukkan",
        save: "Simpan",
        yourSharePhrase: "Frasa Berbagi Anda",
        copy: "Salin",
        share: "Bagikan",
        proceed: "Lanjutkan",
        viewPassphrase: "Lihat Frasa Sandi",
        editList: "Edit Daftar",
        addAtLeastOneWord: "Silakan tambahkan setidaknya satu kata",
        passphraseCopied: "Frasa sandi disalin ke clipboard!",
        copyPassphrase: "Salin frasa sandi ini:",
        invalidPassphrase: "Frasa sandi tidak valid",
        visitDendriteAT: "Kunjungi Dendrite AT",
        languageSettings: "Pengaturan Bahasa",
        visionAccessibility: "Aksesibilitas Visual",
        resourceSettings: "Pengaturan Sumber Daya",
        emptyStateMessage: "Kata-kata Anda akan muncul di sini. Mulai mengetik di atas!"
    },
    symbols: {
        name: "👁️🖐️💬",
        signShare: "✋ 📤",
        pageTitle: "✋ 📤 - ASL 📝",
        createNewList: "➕ 📝",
        retrieveList: "🔍 📝",
        enterPassphrase: "🔑 ⌨️",
        load: "📥",
        enterWord: "💬 ⌨️",
        enter: "✅",
        save: "💾",
        yourSharePhrase: "🔑 📤",
        copy: "📋",
        share: "📤",
        proceed: "➡️",
        viewPassphrase: "👁️ 🔑",
        editList: "✏️ 📝",
        addAtLeastOneWord: "⚠️ ➕ 💬",
        passphraseCopied: "✅ 📋",
        copyPassphrase: "📋 🔑",
        invalidPassphrase: "❌ 🔑",
        visitDendriteAT: "🌐 Dendrite AT",
        languageSettings: "🌍 ⚙️",
        visionAccessibility: "👁️ ♿",
        resourceSettings: "📚 ⚙️",
        emptyStateMessage: "💬 ⬆️ ⌨️"
    },
    ko: {
        name: "한국어",
        signShare: "수화 공유",
        pageTitle: "수화 공유 - ASL 단어 목록",
        createNewList: "새 목록 만들기",
        retrieveList: "목록 불러오기",
        enterPassphrase: "암호 문구 입력",
        load: "불러오기",
        enterWord: "단어 입력",
        enter: "입력",
        save: "저장",
        yourSharePhrase: "공유 문구",
        copy: "복사",
        share: "공유",
        proceed: "계속",
        viewPassphrase: "암호 문구 보기",
        editList: "목록 편집",
        addAtLeastOneWord: "최소 한 단어를 추가하세요",
        passphraseCopied: "암호 문구가 클립보드에 복사되었습니다!",
        copyPassphrase: "이 암호 문구 복사:",
        invalidPassphrase: "잘못된 암호 문구",
        visitDendriteAT: "Dendrite AT 방문",
        languageSettings: "언어 설정",
        visionAccessibility: "시각 접근성",
        resourceSettings: "리소스 설정",
        emptyStateMessage: "단어가 여기에 표시됩니다. 위에서 입력을 시작하세요!"
    },
    tr: {
        name: "Türkçe",
        signShare: "İşaret Paylaş",
        pageTitle: "İşaret Paylaş - ASL Kelime Listeleri",
        createNewList: "Yeni Liste Oluştur",
        retrieveList: "Liste Getir",
        enterPassphrase: "Parola ifadesi girin",
        load: "Yükle",
        enterWord: "Kelime girin",
        enter: "Gir",
        save: "Kaydet",
        yourSharePhrase: "Paylaşım İfadeniz",
        copy: "Kopyala",
        share: "Paylaş",
        proceed: "Devam Et",
        viewPassphrase: "Parola İfadesini Görüntüle",
        editList: "Listeyi Düzenle",
        addAtLeastOneWord: "Lütfen en az bir kelime ekleyin",
        passphraseCopied: "Parola ifadesi panoya kopyalandı!",
        copyPassphrase: "Bu parola ifadesini kopyala:",
        invalidPassphrase: "Geçersiz parola ifadesi",
        visitDendriteAT: "Dendrite AT'yi Ziyaret Et",
        languageSettings: "Dil Ayarları",
        visionAccessibility: "Görsel Erişilebilirlik",
        resourceSettings: "Kaynak Ayarları",
        emptyStateMessage: "Kelimeleriniz burada görünecek. Yukarıda yazmaya başlayın!"
    },
    it: {
        name: "Italiano",
        signShare: "Condividi Segni",
        pageTitle: "Condividi Segni - Elenchi Parole ASL",
        createNewList: "Crea Nuovo Elenco",
        retrieveList: "Recupera Elenco",
        enterPassphrase: "Inserisci la frase segreta",
        load: "Carica",
        enterWord: "Inserisci una parola",
        enter: "Inserisci",
        save: "Salva",
        yourSharePhrase: "La Tua Frase di Condivisione",
        copy: "Copia",
        share: "Condividi",
        proceed: "Procedi",
        viewPassphrase: "Visualizza Frase Segreta",
        editList: "Modifica Elenco",
        addAtLeastOneWord: "Aggiungi almeno una parola",
        passphraseCopied: "Frase segreta copiata negli appunti!",
        copyPassphrase: "Copia questa frase segreta:",
        invalidPassphrase: "Frase segreta non valida",
        visitDendriteAT: "Visita Dendrite AT",
        languageSettings: "Impostazioni Lingua",
        visionAccessibility: "Accessibilità Visiva",
        resourceSettings: "Impostazioni Risorse",
        emptyStateMessage: "Le tue parole appariranno qui. Inizia a digitare sopra!"
    },
    vi: {
        name: "Tiếng Việt",
        signShare: "Chia Sẻ Ký Hiệu",
        pageTitle: "Chia Sẻ Ký Hiệu - Danh Sách Từ ASL",
        createNewList: "Tạo Danh Sách Mới",
        retrieveList: "Lấy Danh Sách",
        enterPassphrase: "Nhập cụm mật khẩu",
        load: "Tải",
        enterWord: "Nhập một từ",
        enter: "Nhập",
        save: "Lưu",
        yourSharePhrase: "Cụm Chia Sẻ Của Bạn",
        copy: "Sao chép",
        share: "Chia sẻ",
        proceed: "Tiếp tục",
        viewPassphrase: "Xem Cụm Mật Khẩu",
        editList: "Chỉnh Sửa Danh Sách",
        addAtLeastOneWord: "Vui lòng thêm ít nhất một từ",
        passphraseCopied: "Đã sao chép cụm mật khẩu vào clipboard!",
        copyPassphrase: "Sao chép cụm mật khẩu này:",
        invalidPassphrase: "Cụm mật khẩu không hợp lệ",
        visitDendriteAT: "Truy cập Dendrite AT",
        languageSettings: "Cài Đặt Ngôn Ngữ",
        visionAccessibility: "Khả Năng Truy Cập Thị Giác",
        resourceSettings: "Cài Đặt Tài Nguyên",
        emptyStateMessage: "Các từ của bạn sẽ xuất hiện ở đây. Bắt đầu nhập ở trên!"
    },
    th: {
        name: "ไทย",
        signShare: "แบ่งปันภาษามือ",
        pageTitle: "แบ่งปันภาษามือ - รายการคำ ASL",
        createNewList: "สร้างรายการใหม่",
        retrieveList: "ดึงรายการ",
        enterPassphrase: "ป้อนวลีรห��ผ่าน",
        load: "โหลด",
        enterWord: "ป้อนคำ",
        enter: "ป้อน",
        save: "บันทึก",
        yourSharePhrase: "วลีแบ่งปันของคุณ",
        copy: "คัดลอก",
        share: "แบ่งปัน",
        proceed: "ดำเนินการต่อ",
        viewPassphrase: "ดูวลีรหัสผ่าน",
        editList: "แก้ไขรายการ",
        addAtLeastOneWord: "โปรดเพิ่มอย่างน้อยหนึ่งคำ",
        passphraseCopied: "คัดลอกวลีรหัสผ่านไปยังคลิปบอร์ดแล้ว!",
        copyPassphrase: "คัดลอกวลีรหัสผ่านนี้:",
        invalidPassphrase: "วลีรหัสผ่านไม่ถูกต้อง",
        visitDendriteAT: "เยี่ยมชม Dendrite AT",
        languageSettings: "การตั้งค่าภาษา",
        visionAccessibility: "การเข้าถึงด้านการมองเห็น",
        resourceSettings: "การตั้งค่าทรัพยากร",
        emptyStateMessage: "คำของคุณจะปรากฏที่นี่ เริ่มพิมพ์ด้านบน!"
    },
    sw: {
        name: "Kiswahili",
        signShare: "Shiriki Ishara",
        pageTitle: "Shiriki Ishara - Orodha za Maneno ya ASL",
        createNewList: "Unda Orodha Mpya",
        retrieveList: "Rudisha Orodha",
        enterPassphrase: "Weka neno la siri",
        load: "Pakia",
        enterWord: "Weka neno",
        enter: "Weka",
        save: "Hifadhi",
        yourSharePhrase: "Neno Lako la Kushiriki",
        copy: "Nakili",
        share: "Shiriki",
        proceed: "Endelea",
        viewPassphrase: "Angalia Neno la Siri",
        editList: "Hariri Orodha",
        addAtLeastOneWord: "Tafadhali ongeza angalau neno moja",
        passphraseCopied: "Neno la siri limenakiliwa kwenye ubao wa kunakili!",
        copyPassphrase: "Nakili neno hili la siri:",
        invalidPassphrase: "Neno la siri si sahihi",
        visitDendriteAT: "Tembelea Dendrite AT",
        languageSettings: "Mipangilio ya Lugha",
        visionAccessibility: "Upatikanaji wa Kuona",
        resourceSettings: "Mipangilio ya Rasilimali",
        emptyStateMessage: "Maneno yako yataonekana hapa. Anza kuandika hapo juu!"
    },
    tl: {
        name: "Tagalog",
        signShare: "Ibahagi ang Senyas",
        pageTitle: "Ibahagi ang Senyas - Mga Listahan ng Salita sa ASL",
        createNewList: "Lumikha ng Bagong Listahan",
        retrieveList: "Kunin ang Listahan",
        enterPassphrase: "Ilagay ang passphrase",
        load: "I-load",
        enterWord: "Maglagay ng salita",
        enter: "Ipasok",
        save: "I-save",
        yourSharePhrase: "Iyong Passphrase sa Pagbabahagi",
        copy: "Kopyahin",
        share: "Ibahagi",
        proceed: "Magpatuloy",
        viewPassphrase: "Tingnan ang Passphrase",
        editList: "I-edit ang Listahan",
        addAtLeastOneWord: "Mangyaring magdagdag ng kahit isang salita",
        passphraseCopied: "Nakopya ang passphrase sa clipboard!",
        copyPassphrase: "Kopyahin ang passphrase na ito:",
        invalidPassphrase: "Di-wastong passphrase",
        visitDendriteAT: "Bisitahin ang Dendrite AT",
        languageSettings: "Mga Setting ng Wika",
        visionAccessibility: "Pagiging Accessible sa Paningin",
        resourceSettings: "Mga Setting ng Mapagkukunan",
        emptyStateMessage: "Ang iyong mga salita ay lalabas dito. Magsimulang mag-type sa itaas!"
    },
    fa: {
        name: "فارسی",
        signShare: "اشتراک‌گذاری اشاره",
        pageTitle: "اشتراک‌گذاری اشاره - لیست‌های واژه ASL",
        createNewList: "ایجاد لیست جدید",
        retrieveList: "بازیابی لیست",
        enterPassphrase: "عبارت عبور را وارد کنید",
        load: "بارگذاری",
        enterWord: "واژه‌ای وارد کنید",
        enter: "ورود",
        save: "ذخیره",
        yourSharePhrase: "عبارت اشتراک‌گذاری شما",
        copy: "کپی",
        share: "اشتراک‌گذاری",
        proceed: "ادامه",
        viewPassphrase: "مشاهده عبارت عبور",
        editList: "ویرایش لیست",
        addAtLeastOneWord: "لطفاً حداقل یک واژه اضافه کنید",
        passphraseCopied: "عبارت عبور در کلیپ‌بورد کپی شد!",
        copyPassphrase: "این عبارت عبور را کپی کنید:",
        invalidPassphrase: "عبارت عبور نامعتبر",
        visitDendriteAT: "بازدید از Dendrite AT",
        languageSettings: "تنظیمات زبان",
        visionAccessibility: "دسترسی‌پذیری بینایی",
        resourceSettings: "تنظیمات منابع",
        emptyStateMessage: "واژه‌های شما اینجا نمایش داده می‌شوند. در بالا شروع به تایپ کنید!"
    },
    ur: {
        name: "اردو",
        signShare: "اشارے شیئر کریں",
        pageTitle: "اشارے شیئر کریں - ASL الفاظ کی فہرستیں",
        createNewList: "نئی فہرست بنائیں",
        retrieveList: "فہرست بازیافت کریں",
        enterPassphrase: "پاس فریز درج کریں",
        load: "لوڈ کریں",
        enterWord: "لفظ درج کریں",
        enter: "درج کریں",
        save: "محفوظ کریں",
        yourSharePhrase: "آپ کا شیئر فریز",
        copy: "کاپی کریں",
        share: "شیئر کریں",
        proceed: "جاری رکھیں",
        viewPassphrase: "پاس فریز دیکھیں",
        editList: "فہرست میں ترمیم کریں",
        addAtLeastOneWord: "براہ کرم کم از کم ایک لفظ شامل کریں",
        passphraseCopied: "پاس فریز کلپ بورڈ میں کاپی ہو گیا!",
        copyPassphrase: "یہ پاس فریز کاپی کریں:",
        invalidPassphrase: "غلط پاس فریز",
        visitDendriteAT: "Dendrite AT ملاحظہ کریں",
        languageSettings: "زبان کی ترتیبات",
        visionAccessibility: "بصری رسائی",
        resourceSettings: "وسائل کی ترتیبات",
        emptyStateMessage: "آپ کے الفاظ یہاں ظاہر ہوں گے۔ اوپر ٹائپ کرنا شروع کریں!"
    },
    he: {
        name: "עברית",
        signShare: "שתף שפת סימנים",
        pageTitle: "שתף שפת סימנים - רשימות מילים ASL",
        createNewList: "צור רשימה חדשה",
        retrieveList: "אחזר רשימה",
        enterPassphrase: "הזן ביטוי סיסמה",
        load: "טען",
        enterWord: "הזן מילה",
        enter: "הזן",
        save: "שמור",
        yourSharePhrase: "ביטוי השיתוף שלך",
        copy: "העתק",
        share: "שתף",
        proceed: "המשך",
        viewPassphrase: "הצג ביטוי סיסמה",
        editList: "ערוך רשימה",
        addAtLeastOneWord: "אנא הוסף לפחות מילה אחת",
        passphraseCopied: "ביטוי הסיסמה הועתק ללוח!",
        copyPassphrase: "העתק ביטוי סיסמה זה:",
        invalidPassphrase: "ביטוי סיסמה לא תקין",
        visitDendriteAT: "בקר ב-Dendrite AT",
        languageSettings: "הגדרות שפה",
        visionAccessibility: "נגישות ראייה",
        resourceSettings: "הגדרות משאבים",
        emptyStateMessage: "המילים שלך יופיעו כאן. התחל להקליד למעלה!"
    },
    uk: {
        name: "Українська",
        signShare: "Поділитися жестами",
        pageTitle: "Поділитися жестами - Списки слів ASL",
        createNewList: "Створити новий список",
        retrieveList: "Отримати список",
        enterPassphrase: "Введіть парольну фразу",
        load: "Завантажити",
        enterWord: "Введіть слово",
        enter: "Ввести",
        save: "Зберегти",
        yourSharePhrase: "Ваша фраза для обміну",
        copy: "Копіювати",
        share: "Поділитися",
        proceed: "Продовжити",
        viewPassphrase: "Переглянути парольну фразу",
        editList: "Редагувати список",
        addAtLeastOneWord: "Будь ласка, додайте принаймні одне слово",
        passphraseCopied: "Парольну фразу скопійовано в буфер обміну!",
        copyPassphrase: "Скопіюйте цю парольну фразу:",
        invalidPassphrase: "Невірна парольна фраза",
        visitDendriteAT: "Відвідати Dendrite AT",
        languageSettings: "Налаштування мови",
        visionAccessibility: "Візуальна доступність",
        resourceSettings: "Налаштування ресурсів",
        emptyStateMessage: "Ваші слова з'являться тут. Почніть друкувати вище!"
    },
    pl: {
        name: "Polski",
        signShare: "Udostępnij Znaki",
        pageTitle: "Udostępnij Znaki - Listy Słów ASL",
        createNewList: "Utwórz Nową Listę",
        retrieveList: "Pobierz Listę",
        enterPassphrase: "Wprowadź hasło",
        load: "Załaduj",
        enterWord: "Wprowadź słowo",
        enter: "Wprowadź",
        save: "Zapisz",
        yourSharePhrase: "Twoje Hasło Udostępniania",
        copy: "Kopiuj",
        share: "Udostępnij",
        proceed: "Kontynuuj",
        viewPassphrase: "Zobacz Hasło",
        editList: "Edytuj Listę",
        addAtLeastOneWord: "Proszę dodać co najmniej jedno słowo",
        passphraseCopied: "Hasło skopiowane do schowka!",
        copyPassphrase: "Skopiuj to hasło:",
        invalidPassphrase: "Nieprawidłowe hasło",
        visitDendriteAT: "Odwiedź Dendrite AT",
        languageSettings: "Ustawienia Języka",
        visionAccessibility: "Dostępność Wzrokowa",
        resourceSettings: "Ustawienia Zasobów",
        emptyStateMessage: "Twoje słowa pojawią się tutaj. Zacznij pisać powyżej!"
    },
    ms: {
        name: "Bahasa Melayu",
        signShare: "Kongsi Isyarat",
        pageTitle: "Kongsi Isyarat - Senarai Perkataan ASL",
        createNewList: "Cipta Senarai Baharu",
        retrieveList: "Dapatkan Senarai",
        enterPassphrase: "Masukkan frasa laluan",
        load: "Muat",
        enterWord: "Masukkan perkataan",
        enter: "Masukkan",
        save: "Simpan",
        yourSharePhrase: "Frasa Perkongsian Anda",
        copy: "Salin",
        share: "Kongsi",
        proceed: "Teruskan",
        viewPassphrase: "Lihat Frasa Laluan",
        editList: "Edit Senarai",
        addAtLeastOneWord: "Sila tambah sekurang-kurangnya satu perkataan",
        passphraseCopied: "Frasa laluan disalin ke papan klip!",
        copyPassphrase: "Salin frasa laluan ini:",
        invalidPassphrase: "Frasa laluan tidak sah",
        visitDendriteAT: "Lawati Dendrite AT",
        languageSettings: "Tetapan Bahasa",
        visionAccessibility: "Kebolehcapaian Penglihatan",
        resourceSettings: "Tetapan Sumber",
        emptyStateMessage: "Perkataan anda akan muncul di sini. Mula menaip di atas!"
    },
    am: {
        name: "አማርኛ",
        signShare: "ምልክት አጋራ",
        pageTitle: "ምልክት አጋራ - ASL ቃላት ዝርዝሮች",
        createNewList: "አዲስ ዝርዝር ፍጠር",
        retrieveList: "ዝርዝር ውሰድ",
        enterPassphrase: "የይለፍ ሐረግ አስገባ",
        load: "ጫን",
        enterWord: "ቃል አስገባ",
        enter: "አስገባ",
        save: "አስቀምጥ",
        yourSharePhrase: "የእርስዎ የማጋራት ሐረግ",
        copy: "ቅዳ",
        share: "አጋራ",
        proceed: "ቀጥል",
        viewPassphrase: "የይለፍ ሐረግ ይመልከቱ",
        editList: "ዝርዝር አርትዕ",
        addAtLeastOneWord: "እባክዎን ቢያንስ አንድ ቃል ያክሉ",
        passphraseCopied: "የይለፍ ሐረግ ወደ ቅንጥብ ሰሌዳ ተቀድቷል!",
        copyPassphrase: "ይህን የይለፍ ሐረግ ቅዳ:",
        invalidPassphrase: "ልክ ያልሆነ የይለፍ ሐረግ",
        visitDendriteAT: "Dendrite AT ይጎብኙ",
        languageSettings: "የቋንቋ ቅንብሮች",
        visionAccessibility: "የእይታ ተደራሽነት",
        resourceSettings: "የግብአት ቅንብሮች",
        emptyStateMessage: "ቃላትዎ እዚህ ይታያሉ። ከላይ መተየብ ይጀምሩ!"
    }
};

let currentLanguage = 'en';

function t(key) {
    return translations[currentLanguage][key] || translations['en'][key] || key;
}

function setLanguage(lang) {
    if (!translations[lang]) {
        console.warn(`Language ${lang} not found, defaulting to English`);
        lang = 'en';
    }
    
    currentLanguage = lang;
    localStorage.setItem('language', lang);
    updateUI();
}

function updateUI() {
    document.title = t('pageTitle');
    
    document.querySelectorAll('[data-i18n]').forEach(element => {
        const key = element.getAttribute('data-i18n');
        const translation = t(key);
        
        if (element.tagName === 'INPUT' || element.tagName === 'TEXTAREA') {
            if (element.placeholder !== undefined) {
                element.placeholder = translation;
            }
        } else {
            element.textContent = translation;
        }
    });
    
    document.querySelectorAll('[data-i18n-title]').forEach(element => {
        const key = element.getAttribute('data-i18n-title');
        element.title = t(key);
    });
    
    document.querySelectorAll('[data-i18n-aria]').forEach(element => {
        const key = element.getAttribute('data-i18n-aria');
        element.setAttribute('aria-label', t(key));
    });
    
    document.documentElement.lang = currentLanguage;
    
    if (['ar', 'fa', 'ur', 'he'].includes(currentLanguage)) {
        document.documentElement.dir = 'rtl';
    } else {
        document.documentElement.dir = 'ltr';
    }
}

function initLocalization() {
    const savedLanguage = localStorage.getItem('language') || 'en';
    setLanguage(savedLanguage);
}

function getAvailableLanguages() {
    return Object.keys(translations).map(code => ({
        code,
        name: translations[code].name
    }));
}
